### ISSUE TITLE
Thehive conf.d configuration

### ISSUE THREAD

**Issue by fareedfauzi** [vace-sec/logstash-output-thehive#1]
Hey, thanks for the plugin.

Can you guide me on how to configure this plugin in conf.d? What field its required?

![image](https://user-images.githubusercontent.com/56353946/78396160-6fce2280-7621-11ea-9c1d-b5142ea6fee3.png)

From the below error, it seems like I need those field. Can you give me an example of those field?

![image](https://user-images.githubusercontent.com/56353946/78396274-a6a43880-7621-11ea-8951-6e21f4979fd2.png)

Thanks!

**Comment by sprungknoedl** [comment]
There are some required fields for this plugin, all of them of type string/text.

The first batch define the connection parameters how to talk to the TheHive Alert API:
- url: e.g. `http://127.0.0.1:9000/api/alert`
- key: the API key configured in the users section of TheHive with privileges to create alerts

The other required fields directly map to TheHive API. It might be best to read the documentation there: [TheHiveDocs](https://github.com/TheHive-Project/TheHiveDocs/blob/master/api/alert.md)
- title
- description
- type
- source
- sourceRef
